### ISSUE TITLE
BIP32 xpub query API

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#11]
@weilu @jprichardson

Aside from the massive privacy implications sharing this information could have. 
If a user uses the same wallet software for the given time frame, the resultant block-explorer would probably know all of the users addresses anyway?

Naturally, there is a major security concern as well if any of a users private keys are leaked, as is shown [here](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/crypto.js#L46).

**Comment by jprichardson** [comment]
My first question, which APIs even offer this capability? Or are you planning on it with HB v2?

**Comment by dcousens** [comment]
@jprichardson good point, at this point, only https://blockchain.info/ offer it.  But its one of those things that will probably appear if demand for it occurs.

**Comment by weilu** [comment]
I'm all for it. It will make HD wallet apps much simpler. Privacy and security are definitely valid concerns. Security wise, it's been established that one should keep their private keys safe, period. In this case, the loss/compromise of one private key potentially leads to loss of more than just funds associated with that private key. It's something HD wallet users should be informed of, but I don't think it'd be fault/liability of the APIs that provide BIP32 xpub query functionalities. Like @dcousens said privacy is not a new issue that this API will bring to blockchain APIs. All things considered, my vote is +1

**Comment by dcousens** [comment]
@maraoz thoughts on this?

**Comment by maraoz** [comment]
I'm not sure how this could be implemented properly, to be honest. BIP32 is a really generic standard, and to the best of my knowledge, you can't derive all possible child nodes for a xpub. How's this supposed to work? Maybe it makes sense to use a specific derivation strategy, say BIP44 or BIP45

**Comment by dcousens** [comment]
You would just expand the xpub until no used children were found.    No
derivation strategy is necessary.

**Comment by dcousens** [comment]
Max depth of 1.  No children children.

**Comment by dcousens** [comment]
To elaborate,  you would only ever compute on demand with recommended
server side caching encrypted using the `hash(xpub)` as the key.

Naturally, this is only a server side precaution and could be removed.

**Comment by dcousens** [comment]
The API would mimic the address API with optional children range pagination.

**Comment by maraoz** [comment]
So you would be listing transactions for addresses derived from `m/*` paths of a given xpub? That'd miss all [BIP43](https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki) derived addresses, or any case using hardened keys. 
I don't see this as very useful, given most BIP32 use cases you can find nowadays. Just my 2 cents.

**Comment by dcousens** [comment]
The given xpub could lie at `m/0/44/0'/`.   It doesn't matter?

**Comment by maraoz** [comment]
Ah... I see now. OK, looks good to me

**Comment by dcousens** [comment]
Going to close this,  as it is simply too unsafe.
A bloom filter is much safer and doesn't expose the master public key.
