### ISSUE TITLE
Streaming Specification

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#13]
## Watch.Addresses.Transactions

**Parameters:** Array of addresses to watch

Returns [relevant] transactions as they occur

``` javascript
{
  txId: "c7736a0a0046d5a8cc61c8c3c2821d4d7517f5de2bc66a966011aaa79965ffba",
  txHex: "01000000011c1020c1114820e7c44e12e8 ... much hex"
}
```

## Watch.Blocks.Latest

**Parameters:** Minimum depth [default of 0]

Returns blocks as they occur (subjective to chain re-organizations)

``` javascript
{
  blockId: "00000000000000001b701ecd0cf2b7a7742a320e9a06a506227ee345b5735d13",
  blockHex: "020000003bef0d0b88737698572aa5c78 ... much hex"
}
```
----

This is just my first pass at what I think will be useful, and naturally this will be typically implemented over a WebSocket.

**Comment by dcousens** [comment]
ping @jprichardson @weilu @rubensayshi

**Comment by rubensayshi** [comment]
address transactions are 1 time events, only when first seen by the node or do you want to receive events on their first confirmation too?  
I guess it makes more sense to just wait for blocks and then check if your zero-conf TXs are in there.

though having to receive every blockHex just to be able to know if your tx was confirmed might be a bit much on data?

**Comment by jprichardson** [comment]
> address transactions are 1 time events, only when first seen by the node or do you want to receive events on their first confirmation too?

Seems to me that it should be just when it hits the node and not on confirmations.

> though having to receive every blockHex just to be able to know if your tx was confirmed might be a bit much on data?

Totally agree, `blockHex` is unnecessary and heavyweight. Ultimately these specs should be designed in such a way that hopefully API providers want to conform to them, right? If we don't include `blockHex`, should we even include `txHex`?

**Comment by fanatid** [comment]
> If we don't include blockHex, should we even include txHex?

I think notifications must be light as possible (blockid and height for new block, address and txid for new transaction).

I'm already implement notifications for [chain](https://chain.com) and [insight-api](https://github.com/bitpay/insight-api) in [blockchainjs](https://github.com/fanatid/blockchainjs). I hope this will be helpful for some common-blockchain modules.

**Comment by weilu** [comment]
> I think notifications must be light as possible (blockid and height for new block, address and txid for new transaction).

I agree, for the sake of maximum compatibility. One can always query the http end points for more info once they get the notification. We could define endpoints that require more data returned, and we could do the http query work under the hood for APIs that lack direct support, but it could very well be suboptimal, as devs might want to batch up requests, and query periodically when the user is not actively using the app.

I'd suggest also adding the number of confirmations (optional?) for the address tx watch, as some API notifies multiple times as more blocks come in, chain.com for example: https://chain.com/docs#notifications-definitions.

**Comment by dcousens** [comment]
@fanatid you can't really do

> address and txId

Without a lot more work, its much easier to just return the `txId` solely for a given filter, then leave it up to the user to determine what addresses it may or may not be associated with (remember, it is a 1-to-many relationship).

**Comment by dcousens** [comment]
Maintaining a bloom filter query is more optimal then the streaming interface,  both in terms of data and in maintaining the connection.
I'm going to close this in favour of https://github.com/common-blockchain/common-blockchain/issues/16.
