### ISSUE TITLE
Bloom filters

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#16]
The bloom filter could be applied to the following aspects of the `0.3.0` API (subject to any changes for `0.4.0`).
- Blocks.Transactions
- Transactions.Latest

Each of the above end points would accept an optional bloom filter to apply to the return values, that is, the filter would be used to check each transaction contains an [address/script](https://github.com/common-blockchain/common-blockchain/issues/17) that is in the bloom filter.

The code could look like the following:

``` javascript
var bitcoin = require('bitcoinjs-lib')
var addresses = ["mpRZxxp5FtmQipEWJPa1NY9FmPsva3exUd", ..]
var scripts = addresses.map((x) => { return bitcoin.Address.toOutputScript(x) }

// currently an unknown API
var filter = new BloomFilter()
scripts.forEach(x => filter.insert(x))

blockchain.blocks.transactions(
  "00000000dd2a3fcde98fb59e2c3cee5b8b8bc183f45070152abf501b6fa7cb7c",
  filter,
  function(err, results) {
    // ...
  }
)
```

**Comment by dcousens** [comment]
This is definitely not something that exists or is going to cross-compatible across nodes, so it will have to follow that we push this kind of API to the nodes through requests and committing to [insight-api](https://github.com/bitpay/insight-api) and what not.

**Comment by dcousens** [comment]
> `Addresses.*` / `ScriptPubKeys.*` - see #17 

I think out of all of them, this will be the most difficult to implement server side, simply because of how the queries are going to work.   I'll have to think into how this could possible work, but, it would be ideal.

**Comment by dcousens** [comment]
For the record,  it should be recognized the purpose of this isn't for privacy,  but for query efficiency.

**Comment by xloem** [comment]
I believe webcoin uses bloom filters -- https://github.com/mappum/webcoin

**Comment by dcousens** [comment]
@jprichardson what are your thoughts on the upper limits of mobile bandwidth usage for say users in the United States?

**Comment by jprichardson** [comment]
@dcousens is 8ight (?) making a move to the US market 😝 ? I don't think this is an issue i.e. I think SPV over mobile is not a problem in today's US mobile market. Monthly data allowances are anywhere from 10 GB to 24 GB and the bandwidth use to be much higher in the 30 Mbs to 50 Mbs range, but lately seems down to around 10 Mbs. Regardless, even less than that could handle SPV just fine. As an example, I have no problem using Breadwallet here.

**Comment by dcousens** [comment]
@jprichardson haha,  no,  I'm just thinking what are some solid bounds so I can play with a SPV-like solution without blowing a users privacy... whilst staying realistic.
