### ISSUE TITLE
List of compliant implementations?

### ISSUE THREAD

**Issue by olalonde** [common-blockchain/common-blockchain#21]
Is there a list of common-blockchain compliant APIs somewhere?

**Comment by jprichardson** [comment]
Not currently. We're deciding if we should move them into this organization or not. 

Here's the unofficial list that I know of:

- https://github.com/weilu/cb-blockr
- https://github.com/dcousens/cb-chain
- https://github.com/dcousens/cb-helloblock (note, this service is shutting down AFAIK)
- https://github.com/jprichardson/cb-insight

More will be coming :)

**Comment by dcousens** [comment]
@jprichardson I'll reply here.   I think its worth moving the repositories to the organization.
@weilu are you up to move cb-blockr for this?

**Comment by dcousens** [comment]
@jprichardson I think a more important question is,  if an API doesn't fully support the CB API, do we still move it into the 'official' organization?

**Comment by jprichardson** [comment]
@dcousens I'm not sure. On one hand, I can see why we wouldn't, as it's incomplete. But on the other hand, others may still get utility. I'd say it probably makes sense to, but the person who 'started' it has ultimate say on how to maintain it. Sort of like how we run `crypto-browserify`. I can't see this being too much of an issue, as we all tend to agree on a lot of code maintenance issues, but it makes sense for one person to have the final say - so it seems the person who started the repo has that final say on that repo. Thoughts?

**Comment by dcousens** [comment]
I've always seen that as the most effective approach.

**Comment by weilu** [comment]
Either way works for me. To @jprichardson's point, I do think people tend to be more responsive/responsible when the repo is under their own name

**Comment by dcousens** [comment]
@weilu as JP said,  it may not be under their name, but they are still
owners as such, they still give the final say.

**Comment by rubensayshi** [comment]
https://api.blocktrail.com/cb/v0.2.1/BTC and https://api.blocktrail.com/cb/v0.2.1/tBTC  
all 0.2.1 endpoints implemented except Blocks.Get (Blocks.Summary is).

**Comment by rubensayshi** [comment]
I unfortunately have be very conservative with my FOSS time atm because of a lot of stuff going on in other areas, but if cb-tester would be completely updated to 0.3.2 then I can probably also implement that one too

**Comment by dcousens** [comment]
@rubensayshi I'm going to bump `cb-tester` to `0.3.2`,  lets see if we can get it ready ASAP.

**Comment by dcousens** [comment]
Adding to the README
