### ISSUE TITLE
Add Addresses.Balance?

### ISSUE THREAD

**Issue by jprichardson** [common-blockchain/common-blockchain#22]
`Addressess.Summary` may be too request intensive if the Blockchain API endpoint doesn't provide anything related to transactions and thus it could be costly for the API to have to compute `totalReceived` or `txCount`. Having `Addresses.Balance` would just provide the `balance`. In fact, I'd be in favor of axing `Summary` altogether. We should start with a simple bare bones common-blockchain so that we can ensure that implementations are simple and straightforward. IMHO `common-blockchain` is doing too much too early.

**Comment by dcousens** [comment]
@jprichardson I think this would be better solved by a query language such as GraphQL (see https://github.com/common-blockchain/common-blockchain/issues/23).

Re-open if you think otherwise.

**Comment by jprichardson** [comment]
If we're going the GraphQL route (which I think we should strongly consider), then yes, I agree. Most methods would be axed ASFAICT. But if we're not, then I think this deserves some thought.

Either way, I'm fine with waiting until we decided on GraphQL. Reopening to keep note of.

**Comment by dcousens** [comment]
@jprichardson :+1: agree.

I mostly wanted to just get settled on the last version of the non-Graph QL specification, because it may be a smaller while and I don't want to leave this half hanging.

**Comment by dcousens** [comment]
Probably NACK on this.  Its too subjective and completely unclear how it would be calculated, especially with things like RBF coming along.

**Comment by jprichardson** [comment]
> Probably NACK on this. Its too subjective and completely unclear how it would be calculated, especially with things like RBF coming along.

In that case, are you planning on nixing `Summary` then? As `Summary` includes the `balance` :stuck_out_tongue_winking_eye:

**Comment by dcousens** [comment]
@jprichardson sure am.

**Comment by jprichardson** [comment]
@jprichardson sure am.

:+1:

**Comment by dcousens** [comment]
Instead I'm opting for a transaction count end point.  Something that just gives you the number of known transactions relative to a script.

It can be used for all the same usages, and, while subjective, doesn't require any complex logic and is a super simple query for most database indexes too.
