### ISSUE TITLE
Investigate GraphQL

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#23]
@rubensayshi this could be the best way to move forward once it is standardized.
Especially in relation to complex queries where all you want is the minimal amount of *relevant* data.

**Comment by rubensayshi** [comment]
hmm interesting idea

**Comment by dcousens** [comment]
A good video for explaining [GraphQL](https://www.youtube.com/watch?v=WQLzZf34FJ8).

**Comment by dcousens** [comment]
Probably not going to happen
