### ISSUE TITLE
wrapper for bitcore-node, fullnode

### ISSUE THREAD

**Issue by mvayngrib** [common-blockchain/common-blockchain#24]
[bitcore-node](https://github.com/bitpay/bitcore-node), [fullnode](https://github.com/ryanxcharles/fullnode) are the contenders for JS-based full nodes (though bitcore-node uses bitcoind). It would be awesome to use a common-blockchain API to talk to those two.

Also, maybe someone knows another JS-based full node / bitcoind wrapper?

**Comment by fanatid** [comment]
[chromanode](https://github.com/chromaway/chromanode) by [chromaway](http://chromaway.com/)

**Comment by mvayngrib** [comment]
@fanatid thanks!

**Comment by dcousens** [comment]
@fanatid but no common-blockchain support? :(

**Comment by fanatid** [comment]
@dcousens  API of chromanode still have status WIP, probably we will change db schema in nearest time again.. any suggestion about api are useful! Instead common-blockchain we use [blockchainjs](http://github.com/chromaway/blockchainjs) that more than just block explorer interface, for example blockchainjs have such functionality as SPV.

**Comment by dcousens** [comment]
Indeed,  we [intend to add bloom filters very soon](https://github.com/common-blockchain/common-blockchain/issues/16) to common-blockchain,  is there any other aspects of SPV you were thinking of?

**Comment by fanatid** [comment]
bloom filters is good idea! I hope that I add this in next major release of chromanode.
block explorer with SPV must have next methods:
1) get headers as chunks ([in chromanode](https://github.com/chromaway/chromanode/blob/master/docs/API_v2.md#query))
2) calculate merkle tree for txid ([in chromanode](https://github.com/chromaway/chromanode/blob/master/docs/API_v2.md#merkle))
