### ISSUE TITLE
Bitpay Insight API doesn't have endpoint to get latest transaction.

### ISSUE THREAD

**Issue by hyzhak** [common-blockchain/common-blockchain#25]
Hello guys! Some APIs doesn't provide endpoint to get latest transaction. They have only endpoint `/txs` which requires `addressHash` or `blockhash` only parameter https://github.com/bitpay/insight-api/blob/master/lib/index.js#L111 and https://github.com/bitpay/insight-api/blob/master/lib/transactions.js#L247.

So is there any sense to have it? https://github.com/common-blockchain/common-blockchain/blob/master/types.json#L108
It breaks for example this wrapper https://github.com/jprichardson/cb-insight.

**Comment by dcousens** [comment]
Fetching the mempool can be costly, even if you only fetch `txId`s,  maybe its not worth supporting without a filter of some sort?

**Comment by hyzhak** [comment]
@dcousens yes, good point
