### ISSUE TITLE
Ongoing development

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#28]
I don't personally have the time for this any more,  and I don't think it garnered enough community support due to the inconsistencies at the base.

Thoughts on whether we keep the organization active or no?

**Comment by jprichardson** [comment]
I think it was a great idea and I still think there's merit to the overall idea, but I'm in your boat as well. I don't think it hurts to leave the org open (I probably have a bit of sentimentality to these things), but if you want to kill the org, I totally understand and support the decision.

**Comment by dcousens** [comment]
I understand the sentimentality,  I just worry about ongoing support and leaving a graveyard of projects serving only to confuse.

**Comment by jprichardson** [comment]
> Maybe just an npm deprecate for now and we leave the org?

Big picture, I don't care either way. If you have a slight preference to nuking the org, just do it - I support it.

**Comment by dcousens** [comment]
Leaving everything as is
