### ISSUE TITLE
Use JSON properties to enforce uniqueness

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#6]
Rather than:

``` javascript
[
  {
    address: "mpNDUWcDcZw1Teo3LFHvr8usNdwDLKdTaY",
    balance: 100000,
    totalReceived: 430000,
    txCount: 3
  },
  ...
]
```

We could adopt the format:

``` javascript
{
  "mpNDUWcDcZw1Teo3LFHvr8usNdwDLKdTaY": {
    balance: 100000,
    totalReceived: 430000,
    txCount: 3
  },
  ...
}
```

To enforce that no results are repeated/duplicated.  This language-given contract saves us from having to audit possibly erroneous results from a provider, and overall increase our safety by using the type system itself to guarantee it.

Unfortunately, this also makes for a slightly less convenient method of operation in regards to functional Array operations disappearing. 

@weilu, we've discussed this before, but just wanted to know your thoughts.

**Comment by dcousens** [comment]
If libraries like [lodash](https://lodash.com/docs#forEach) (for example) are in use, then the inconveniences of this format mostly disappear.

**Comment by CodersBrothers** [comment]
I prefeer second way, with key.

**Comment by jprichardson** [comment]
Although I'd be fine with the change, it feels a bit unnecessary, unless you ran into a practical example of a problem? Either way, the functional aspect isn't lost. Just use `Object.keys` in conjunction with `Array.prototype.map`.

**Comment by dcousens** [comment]
That would be a mapping of keys,  not values.   No better than 'for in'.

I have no practical example,  but it is a possibility.

Why leave it open as a possibility at all if we can assert a particular
behavior using the type system we already have.

**Comment by weilu** [comment]
@dcousens the use case in this library I can think of is when one queries transactions of multiple addresses. If the server side API is poorly designed it might return a transaction that involves n addresses specified n times. IMHO it's a server side design concern. We could enforce the uniqueness on with test cases in common-blockchain but that's as far as I'm willing to go. 

Addresses as keys could be dangerous -- information could be overwritten when it should have been merged.

With the use case and the downside I can think of, I'm not convinced that the proposed change has more benefit than harm.

**Comment by dcousens** [comment]
> Addresses as keys could be dangerous -- information could be overwritten when it should have been merged.

Do you have an example for this?

**Comment by weilu** [comment]
Off the top of my head I have an example from some early implementation of Hive: Blockr has an `amount` field in the tx response. It can be positive or negative and is relative to the address specified. It's like the transaction from a specific address' point of view. When I aggregate transactions that number was overwritten multiple times in some cases, resulted in erroneous outcome.

**Comment by weilu** [comment]
You may argue that it's stupid careless implementation. You may be right. But I'd argue that it's always easier to de-duplicate than to recover lost information.

**Comment by dcousens** [comment]
But in your case, the problem was that you have to de-duplicate multiple sets of data because it was ordered in strange ways.

**Comment by weilu** [comment]
No this leads to data being overwritten silently, which is exactly the danger I was trying to highlight

**Comment by dcousens** [comment]
I'm not sure I understand still, can you provide an example in code?

**Comment by weilu** [comment]
Data returned from blockr:

```
"data": [
  {
    "address": "addr1",
    "txs": [
      {
        "tx": "txid1",
        "amount": 0.001,
      },
      {
        "tx": "txid2",
        "amount": 0.0002,
      }
    ]
  },
  {
    "address": "addr2",
    "txs": [
      {
        "tx": "txid1",
        "amount": -0.005
      }
    ]
  },
]
```

If we were to collect all transactions using an object with txids as keys (same idea as using addresses as keys),  the `amount` will be overwritten once for `txid1` whereas the right thing to do here in order to answer "how does one transaction affect the balance of my collection of addresses" would be adding the amounts together: `0.001 + (-0.005) = -0.004`. Does it make sense? 

What are your use cases that argue __for__ the proposed change?

**Comment by dcousens** [comment]
@weilu I don't see how that problem affects us.  The point is we are enforcing the ability to NOT have duplicates.  We are not dealing with multiple collections, we are dealing with one.

> What are your use cases that argue for the proposed change?

Safety, harnessing the type system to do it for us.

**Comment by dcousens** [comment]
Added to `0.3.0` milestone, but that is in terms of reaching a decision, not implementing.

**Comment by weilu** [comment]
> Safety, harnessing the type system to do it for us.

Again, "safety" is arguable. I still believe that the danger of silent overwrites are more dangerous than having duplicates.

Another point against using objects to represent a collection is that javascript objects are awkward to work with compared to simple arrays, as illustrated by @jprichardson's example above. 

If all you want is to enforce uniqueness, we can use objects internally and not change the return type of endpoints. Such API level stability is something I as a CB dev and user can appreciate.

**Comment by dcousens** [comment]
@weilu I guess who do you think will be more compliant to the specification?

The developer using the library, or the developer implementing the API for all to use.
The latter is easily tested, the former is not.

I think harnessing keys will improve safety in general.

**Comment by dcousens** [comment]
@rubensayshi what are your thoughts on this?

**Comment by rubensayshi** [comment]
as the implementor of the API I don't really get what you're worried about, why would it not be unique xD

as the user or the API / lib, both have advantages.  
 - I like not having to loop over the whole list and create an object keyed with the address when I want to be able to easily look up data for a specific address.
 - but I also don't really like using `Object.keys` all the freakin time...

considering the first case is probably less relevant for an wallet-like application I'd stick to a list and just trust the API to give you a unique list, if you're so distrustful of an API that you think it might not give a unique list when the spec says it should then I think there are deeper problems ;-)

**Comment by dcousens** [comment]
@rubensayshi 

> as the implementor of the API I don't really get what you're worried about, why would it not be unique xD

Famous last words.    Please ping me when you stop sending duplicate data for `addresses/transactions`.

**Comment by dcousens** [comment]
I'm personally still in favour of this.
@rubensayshi any change of heart?

**Comment by rubensayshi** [comment]
I've typed so many `Object.keys().forEach` in the past months, I'm fine with it now xD

**Comment by weilu** [comment]
@dcousens my vote still goes to array.
