### ISSUE TITLE
Transaction.GetOutput (txId, vout)

### ISSUE THREAD

**Issue by dcousens** [common-blockchain/common-blockchain#7]
@jprichardson @weilu thoughts on this new end point?
Suggested by @sidazhang for use in block-explorer like pages to avoid multiple API calls and tedious transaction parsing. 

I'm not sure.

``` javascript
[
  {
    txId: "c7736a0a0046d5a8cc61c8c3c2821d4d7517f5de2bc66a966011aaa79965ffba",
    scriptPubKey: "61b469ada61f37c620010912a9d5d56646015f16",
    value: 10505,
    vout: 0
  },
  ...
]
```

**Comment by dcousens** [comment]
It would be useful in the case where you don't want to download the entire `txHex` for a previous transaction just to determine the input value for your `txIn`.

**Comment by dcousens** [comment]
I'm not sure I like `spentBy` because it simplifies the `blockchain` such that users might believe it is definitive and not subject to confirmations etc.

**Comment by weilu** [comment]
The first question I have is how good/common is this endpoint supported by popular API providers?

**Comment by jprichardson** [comment]
> The first question I have is how good/common is this endpoint supported by popular API providers?

I'm guessing that it's rare. If I'm wrong, and it's common then I'd be all for it.

Otherwise, I'm of the opinion that minimalism is best. Other libraries or specific implementations that want that feature can include it.

**Comment by dcousens** [comment]
The information can be derived from the full transaction hex,  but the idea
is that if possible, it could use significantly less data to do so.

**Comment by weilu** [comment]
If it's not a commonly supported endpoint, making it part of common blockchain means for most API vendors  it's an additional interface that saves nothing and only more code. For now I think it makes more sense to support this as __method for helloblock only.

Cheers
Wei

**Comment by dcousens** [comment]
This information could easily be derived from the other end points, the main objective is that it *can* be done while using a lot less data.
It does not impose any API changes on behalf of providers.

**Comment by weilu** [comment]
It does require API changes on cb-foo implementations. At this point it's an additional endpoint that doesn't benefit __most__ cb-foo libraries. 

If you __really__ want this in CB badly, we could provide a default/fallback implementation in common-blockchain that uses `Transaction.Get`. That way you get what you want; an average cb-foo doesn't have to add the same chunk of code to support an interface that doesn't benefit its users performance wise; and cb-foo devs can implement this interface as providers start to support it.

**Comment by dcousens** [comment]
@weilu this end point would be beneficial IMHO, it allows inspection of previously unspent transaction outs without downloading the entire blockchain.  I can only see that as a beneficial API to have, even though it means for many implementations, you'll just be downloading the full transaction as you currently have to.

**Comment by weilu** [comment]
@dcousens it's beneficial for one API at the moment. Like I said, if you __really__ want this, provide a default/fallback so other APIs don't have to worry about it.

**Comment by dcousens** [comment]
I'd be happy to provide an example fallback code in this issue,  but I don't know how we would easily provide a default fallback given we don't impose a JS API specification yet... @jprichardson
